rose_store/products/urls.py
from django.urls import path
from .views import (
    home,
    flower_api_view,
    product_api_view,
    basket_api_view,
    entourage_api_view,
    branch_api_view,
    package_api_view,
    houseplant_api_view,
    order_api_view,
    gift_api_view,
    send_email_views

)

app_name = "products"

urlpatterns = [
    path("", home),
    path(
        "flowers/", 
        flower_api_view,
        name="flowers"
    ),
    path("products/",
          product_api_view,
          name="products"
    ),
    path("baskets/",
          basket_api_view,
          name="baskets"
    ),
    path("entourages/",
          entourage_api_view,
          name="entourages"
    ),
    path("branches/",
          branch_api_view,
          name="branches"
    ),
    path("packages/",
          package_api_view,
          name="packages"
    ),
    path("houseplants/",
          houseplant_api_view,
          name="houseplants"
    ),
    path("orders/",
          order_api_view,
          name="orders"
    ),
    path("gifts/",
          gift_api_view,
          name="gifts"
    ),
    path("index/",
         send_email_views,
         name="index"
         )
]

rose_store/rose_store/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("products.urls"))
]

rose_store/gifts/models.py
from django.db import models

# Create your models here.
class Gift(models.Model):
    name = models.CharField(max_length=32)
    price = models.FloatField(default=0)
    code = models.PositiveSmallIntegerField(default=0)
    stock_amaount = models.PositiveSmallIntegerField(default=0)
    description = models.TextField(max_length=1024)
    
    def __str__(self) -> str:
        return f"{self.name}"

rose_store/info/models.py
from django.db import models

# Create your models here.
class Branch(models.Model):
    name = models.CharField(max_length=32)
    map_longitude = models.CharField(max_length=32)
    map_latitude = models.CharField(max_length=32)
    address = models.CharField(max_length=32)

    def __str__(self) -> str:
        return f"{self.name}"
    

rose_store/orders/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Order(models.Model):
    STATUSES = (
        ("Placed", "Placed"),
        ("Accepted", "Accepted"),
        ("Preparing", "Preparing"),
        ("Ready to ship", "Ready to ship"),
        ("Shipped", "Shipped"),
        ("Delivered", "Delivered"),
        ("Canceled", "Canceled"),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=16, choices=STATUSES)
    created_at = models.DateTimeField(auto_now_add=True)
    tracking_id = models.CharField(max_length=16)

rose_store/products/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
    flower = models.ForeignKey("Flower", on_delete=models.CASCADE)
    views_count = models.PositiveIntegerField(default=0)
    description = models.TextField(max_length=2000)
    code = models.PositiveSmallIntegerField(default=0)
    price = models.FloatField(default=0)

    def __str__(self) -> str:
        return f"Product ({self.flower})"


class Basket(models.Model):
    flower = models.ForeignKey("Flower", on_delete=models.CASCADE)
    entourage = models.ForeignKey("Entourage", on_delete=models.CASCADE)
    package = models.ForeignKey("Package", on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f"Basket {self.pk}"


class Flower(models.Model):
    name = models.CharField(max_length=32)
    price = models.FloatField(default=0)
    stock_amount = models.PositiveIntegerField(default=0)
    is_main = models.BooleanField(default=False)
    code = models.PositiveSmallIntegerField(default=0)
    
    def __str__(self) -> str:
        return f"{self.name}"
    

class Entourage(models.Model):
    name = models.CharField(max_length=32)
    price = models.FloatField(default=0)
    stock_amount = models.PositiveIntegerField(default=0)
    is_main = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.name}"
    

class Package(models.Model):
    type_name = models.CharField(max_length=32)
    description = models.CharField(max_length=32)
    price = models.FloatField(default=0)

    def __str__(self) -> str:
        return f"{self.type_name}"
    

class Houseplant(models.Model):
    name = models.CharField(max_length=32)
    price = models.FloatField(default=0)
    stock_amount = models.PositiveIntegerField(default=0)
    is_main = models.BooleanField(default=False)
    code = models.PositiveSmallIntegerField(default=0)

    def __str__(self) -> str:
        return f"{self.name}"

    


    

rose_store/gifts/views.py
from django.shortcuts import render

# Create your views here.

rose_store/info/views.py
from django.shortcuts import render

# Create your view

rose_store/orders/views.py
from django.shortcuts import render

# Create your views here.

rose_store/products/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.mail import send_mail
from django.conf import settings

from .models import (
    Flower, 
    Product,
    Basket,
    Entourage,
    Package,
    Houseplant
)
from info.models import Branch
from orders.models import Order
from gifts.models import Gift




def home(request):
    products = Product.objects.all()
    context = {
        "products": products
    }
    return render(request, "products/home.html", context)


def flower_api_view(request):
    flowers = Flower.objects.all()
    context = {
        "flowers": flowers
    }
    return render(request, "products/flowers.html", context)


def product_api_view(request):
    products = Product.objects.all()
    context = {
        "products": products
    }
    return render(request, "products/products.html", context)


def basket_api_view(request):
    baskets = Basket.objects.all()
    context = {
        "baskets": baskets
    }
    return render(request, "products/baskets.html", context)


def entourage_api_view(request):
    entourages = Entourage.objects.all()
    context = {
        "entourages": entourages
    }
    return render(request, "products/entourages.html", context)


def branch_api_view(request):
    branches = Branch.objects.all()
    context = {
        "branches": branches
    }
    return render(request, "products/branches.html", context)


def package_api_view(request):
    packages = Package.objects.all()
    context = {
        "packages":packages
    }
    return render(request, "products/packages.html", context)


def houseplant_api_view(request):
    houseplants = Houseplant.objects.all()
    context = {
        "houseplants": houseplants
    }
    return render(request, "products/houseplants.html", context)


def order_api_view(request):
    orders = Order.objects.all()
    context = {
        "orders": orders
    }
    return render(request, "products/orders.html", context)


def gift_api_view(request):
    gifts = Gift.objects.all()
    context = {
        "gifts": gifts
    }
    return render(request, "products/gifts.html", context)


def send_email_views(request):
    if request.method == 'POST':
        message = request.POST['message']
        email = request.POST['email']
        name = request.POST['name']
        send_mail(
            name,#title
            message, #message
            settings.EMAIL_HOST_USER, #sender if not available considered the default or configered.
            [email, 'kadimovhuseyn35@gmail.com','feridehedov1@gmail.com']
        )
    # message = "spam"
    # email = "quliyev-elcin00@mail.ru"
    # name = "uyyy bimbim"
    # send_mail(
    #     name,#title
    #     message, #message
    #     settings.EMAIL_HOST_USER, #sender if not available considered the default or configered.
    #     [email, 'kadimovhuseyn35@gmail.com','feridehedov1@gmail.com']
    # )
    
    # if request.method == 'POST':
    #     message = request.POST['message']
    #     email = request.POST['email']
    #     name = request.POST['name']
    #     if message and email and name:
    #         send_mail(
    #             name,#title
    #             message, #message
    #             settings.EMAIL_HOST_USER, #sender if not available considered the default or configered.
    #             [email, 'kadimovhuseyn35@gmail.com','feridehedov1@gmail.com']
    #         )
    #     else:
    #         return Http404("voyvoyvoyvoy")
    return render(request, 'products/index.html')

rose_store/products/templates/products/baskets.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p> AG Ciceyim </p>
    <ol>
        {% for basket in baskets %} 
        <li>{{ basket }}</li>
        {%endfor%}
    </ol>
</body>
</html>

rose_store/products/templates/products/branches.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p> AG Ciceyim </p>
    <ol>
        {% for basket in baskets %}
        <li> {{ basket }}</li>
        {%endfor%}
    </ol>
</body>
</html>

rose_store/products/templates/products/entourages.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p> AG Ciceyim </p>
    <ol>
        {% for entourage in entourages %}
        <li> {{ entourage }}</li>
        {%endfor%}
    </ol>

</body>
</html>

rose_store/products/templates/products/flowers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p> AG Ciceyim </p>
    <ol>
        {% for flower in flowers %}
        <li>{{ flower }}</li>
        {%endfor%}
    </ol>
</body>
</html>

rose_store/products/templates/products/gifts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p> AG Ciceyim </p>
    <ol>
        {% for gift in gifts %}
        <li>{{ gift }}</li>
        {%endfor%}
    </ol>
</body>
</html>

rose_store/products/templates/products/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p> AG Ciceyim </p>
    <ol>
        {% for product in products %}
        <li>{{ product }}</li>
        {%endfor%}
    </ol>


</body>
</html>

rose_store/products/templates/products/houseplants.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p> AG Ciceyim </p>
    <ol>
        {% for houseplant in houseplants %}
        <li>{{ houseplant }}</li>
        {% endfor %}
    </ol>
</body>
</html>

rose_store/products/templates/products/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h4>Contact Client</h4>
    <form method="POST" action="{% url 'products:index' %}">
        {% csrf_token %}
        <input type="text" name="name" placeholder="Title of the email" required>
        <br>
        <br>
        <input type="email" name="email" placeholder="The company E-mail address" required>
        <br>
        <br>
        <textarea name="message" placeholder="Message to be delivered" required></textarea>
        <br>
        <br>
        <button class="btn btn-primary mt-2" type="submit">Send</button>
        <br>
        <br>
    </form>
</body>
</html>

rose_store/products/templates/products/orders.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p> AG Ciceyim </p>
    <ol>
        {% for order in orders %}
        <li>{{ order }}</li>
        {% endfor% }
    </ol>
</body>
</html>

rose_store/products/templates/products/packages.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p> AG Ciceyim </p>
    <ol>
        {% for package in packages %}
        <li>{{ package }}</li>
        {%endfor%}
    </ol>
</body>
</html>

rose_store/products/templates/products/products.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p> AG Ciceyim </p>
    <ol>
        {% for product in products %}
        <li>{{ product }}</li>
        {%endfor%}
    </ol>
</body>
</html>